import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'home': 'Home',
      'play': 'Play',
      'play_again': 'Play Again',
      'dark_mode': 'Dark Mode',
      'rate_app': 'Rate App',
      'more_apps': 'More Apps',
      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'refresh': 'Refresh',
      'no_history': 'No history',
      'unknown_event': 'Unknown Event',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',

      // App
      'app_name': 'Minesweeper',
      'home_subtitle': 'Find all mines without detonating one!',
      'select_difficulty': 'SELECT DIFFICULTY',

      // Difficulty
      'diff_beginner': 'Beginner',
      'diff_intermediate': 'Intermediate',
      'diff_expert': 'Expert',
      'diff_custom': 'Custom',

      // Custom sliders
      'custom_rows': 'Rows',
      'custom_cols': 'Cols',
      'custom_mines': 'Mines',

      // Game
      'best_records': 'Best Records',
      'no_record': '--',
      'result_win': 'You Win!',
      'result_lose': 'Boom!',
      'result_lose_sub': 'You hit a mine. Try again!',
      'result_time': 'Time: @{t}s',
      'best_record': '?룇 Best: @{t}s',

      // Extra life
      'extra_life': 'Extra Life!',
      'extra_life_desc': 'Your next mine click is safe.',
      'extra_life_offer': 'Watch an ad to get a second chance!',
      'watch_ad': 'Watch',
      'premium_title': 'Premium',
      'premium_subtitle': 'Unlock all content, remove ads, and use all premium features.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'No Ads',
      'premium_benefit_unlimited': 'Unlock all features',
      'premium_benefit_statistics': 'Detailed statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '7 days',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days',
      'premium_purchase': 'Purchase Premium',
      'premium_restore': 'Restore Purchase',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'The purchase will be restored automatically when you restart the app.',
      'purchase_error': 'Purchase Error',
      'purchase_unavailable': 'In-app purchases are unavailable',
      'purchase_failed': 'Purchase failed. Please try again.',
      'restore_error': 'Restore failed. Please try again.',
      'purchase_success': 'Purchase Completed',
      'premium_ready': 'Premium is now active.',
      'go_premium': 'Go Premium',
      'go_premium_subtitle': 'Unlock all paid features',
    },
    'ko': {
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'ok': '확인',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'home': '홈',
      'play': '시작',
      'play_again': '다시 하기',
      'dark_mode': '다크 모드',
      'rate_app': '앱 평가',
      'more_apps': '더 많은 앱',
      'open_history': '히스토리',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'refresh': '새로고침',
      'no_history': '기록이 없습니다',
      'unknown_event': '알 수 없는 이벤트',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      // App
      'app_name': '지뢰 찾기',
      'home_subtitle': '지뢰를 건드리지 않고 모두 찾으세요!',
      'select_difficulty': '난이도 선택',
      // Difficulty
      'diff_beginner': '초급',
      'diff_intermediate': '중급',
      'diff_expert': '고급',
      'diff_custom': '커스텀',
      // Custom sliders
      'custom_rows': '행',
      'custom_cols': '열',
      'custom_mines': '지뢰',
      // Game
      'best_records': '최고 기록',
      'no_record': '--',
      'result_win': '승리!',
      'result_lose': '펑!',
      'result_lose_sub': '지뢰를 밟았어요. 다시 시도해요!',
      'result_time': '시간: @{t}초',
      'best_record': '🏆 최고: @{t}초',
      // Extra life
      'extra_life': '추가 생명!',
      'extra_life_desc': '다음 지뢰 클릭이 안전해져요.',
      'extra_life_offer': '광고를 시청하고 한 번 더 기회를 받으세요!',
      'watch_ad': '시청',
      // Settings keys
      'sound': '소리',
      'sound_desc': '효과음 재생',
      'haptic': '진동',
      'haptic_desc': '상호작용 시 진동',
      'ads_consent': '광고 동의',
      'ads_consent_desc': '맞춤 광고 설정 사용',
      'language': '언어',
      'clear_data': '로컬 데이터 삭제',
      'clear_data_desc': '소리, 진동, 동의, 언어 설정 및 기록 로그를 초기화합니다.',
      'clear_data_confirm': '모든 로컬 설정과 로그를 삭제합니다. 계속할까요?',
      'confirm': '확인',
      'clear_data_complete': '모든 로컬 데이터가 초기화됐습니다.',
      'loading': '로딩 중...',
      'no_data': '데이터 없음',
      // Premium keys
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 제거, 모든 콘텐츠 잠금 해제, 프리미엄 기능을 이용하세요.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 없음',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '상세 통계',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일',
      'premium_purchase': '프리미엄 구매',
      'premium_restore': '구매 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_success': '결제 완료',
      'premium_ready': '프리미엄이 활성화됐어요.',
      'purchase_unavailable': '인앱 결제를 사용할 수 없어요.',
      'purchase_failed': '결제에 실패했어요. 다시 시도해요.',
      'go_premium': '프리미엄 시작하기',
      'go_premium_subtitle': '유료 기능 모두 잠금 해제',
    },
  };
}

    



